BOX_IMAGE = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
  config.vm.define "web" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "web"
    subconfig.vm.network :private_network, ip: '192.168.111.10'
  end

  config.vm.define "db" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "db"
    subconfig.vm.network :private_network, ip: '192.168.111.11'
  end
end
